#!/usr/bin/env python3

import socket

HOST=''
PORT=1234

s = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
s.bind((HOST,PORT))
s.listen()

while (True):
    conn, addr = s.accept()
s.close()